### ISSUE TITLE
The lastversion cause the not supported error

### ISSUE THREAD

**Issue by lhwsa2010** [godsharp/GodSharp.Socket#14] opened 2021-10-19 02:27 UTC
I use udpclient as service,it always cause error:10045 not supported.But when i use the old version，it work fine.

**Comment by seayxu** [comment] 2021-10-19 07:26
can you show your code?

**Comment by lhwsa2010** [comment] 2021-10-19 07:37
![微信截图_20211019153151](https://user-images.githubusercontent.com/9885614/137863781-fdcce40e-37fd-4ebb-8ae6-36468d370186.png)
This is my code.When i use v2021.206.17.3,it work fine,but when i use the v2021.310.8，it cause error.
![微信截图_20211019153633](https://user-images.githubusercontent.com/9885614/137864468-64b11ad4-db15-458b-9144-36d1d62669cb.png)

**Comment by seayxu** [comment] 2021-10-19 07:43
this problem caused by using keep alive.
it can fixed by disable keep alive:
```
client.UseKeepAlive(false, 500, 500);
```

**Comment by lhwsa2010** [comment] 2021-10-19 07:45
Thanks.It worked!

**Closed as completed** 2021-10-19 08:07 UTC
